#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
#    path: /
#    controller: App\Controller\QuestionController::homepage



app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_vote_count:
    path: /vote/count
    controller: App\Controller\CommentController::number